import { copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { contractReference } from '@vadd/core'
import { vaddHome } from '../paths.js'
import { loadTemplate } from '../prompts/renderer.js'

/**
 * A token only VADD's own generated CLAUDE.md contains.
 *
 * The isolation check is otherwise unfalsifiable: an agent that ignores
 * CLAUDE_CONFIG_DIR and one that honours it both answer most prompts the same
 * way. Echoing this string proves the agent read *our* profile.
 */
export const PROFILE_CANARY = 'VADD-PROFILE-CANARY-7f3a91'

/** `~/.vadd/agent-profiles/claude-code` (design §4.3). */
export function agentProfileDir(): string {
  return join(vaddHome(), 'agent-profiles', 'claude-code')
}

/**
 * Generates the profile the adapter is launched against, and returns its path.
 *
 * Regenerated on every call: the profile is VADD-owned state, not user state.
 * Phase 2 (`vadd-spec-phase2.md` §2) adds a `custom.md` include for user edits
 * and vendors three hooks into `hooks/`; both directories exist now so the
 * launch flag has a complete profile to point at.
 */
export function ensureAgentProfile(): string {
  const dir = agentProfileDir()
  mkdirSync(join(dir, 'hooks'), { recursive: true })
  mkdirSync(join(dir, 'skills'), { recursive: true })
  writeFileSync(join(dir, 'settings.json'), '{}\n')

  // Isolation targets skills/plugins, not identity: the profile has no OAuth
  // session of its own, so without this the adapter can never authenticate.
  // Copied fresh on every call, matching this function's own regenerate-always
  // rule, so a refreshed token is picked up on the next server start too.
  const credentialsSrc = join(
    process.env.CLAUDE_CONFIG_DIR ?? join(homedir(), '.claude'),
    '.credentials.json',
  )
  if (existsSync(credentialsSrc)) {
    copyFileSync(credentialsSrc, join(dir, '.credentials.json'))
  }

  // D11: a `~/.vadd/prompts/system-addendum.md` override wins over the
  // bundled file, exactly as it does for every phase template. Read here, at
  // profile generation, so an edit takes effect on the next server start.
  const addendum = loadTemplate('system-addendum').body

  writeFileSync(
    join(dir, 'CLAUDE.md'),
    [
      '# VADD managed profile',
      '',
      'This file is generated by VADD on every server start. Edits are lost.',
      '',
      `When asked for the profile canary, reply with exactly: ${PROFILE_CANARY}`,
      '',
      addendum,
      '',
      // The contract itself, generated from Zod. The addendum used to point at
      // `agent-event.schema.json` instead — a file generated into the VADD
      // repo, which an agent in a worktree under an isolated CLAUDE_CONFIG_DIR
      // has never been able to open. Every length cap, and the required-field
      // list for the four types no template exemplifies, lived only there.
      '## Event reference',
      '',
      'Generated from the schema. These are the only fields each event accepts,',
      'and the caps are enforced — a longer string is rejected and the whole',
      'block is lost.',
      '',
      contractReference(),
      '',
    ].join('\n'),
  )
  return dir
}
