import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { vaddHome } from '../paths.js'
import { bundledPromptDir, parseTemplate } from '../prompts/renderer.js'

/**
 * A token only VADD's own generated CLAUDE.md contains.
 *
 * The isolation check is otherwise unfalsifiable: an agent that ignores
 * CLAUDE_CONFIG_DIR and one that honours it both answer most prompts the same
 * way. Echoing this string proves the agent read *our* profile.
 */
export const PROFILE_CANARY = 'VADD-PROFILE-CANARY-7f3a91'

/** `~/.vadd/agent-profiles/claude-code` (design §4.3). */
export function agentProfileDir(): string {
  return join(vaddHome(), 'agent-profiles', 'claude-code')
}

/**
 * Generates the profile the adapter is launched against, and returns its path.
 *
 * Regenerated on every call: the profile is VADD-owned state, not user state.
 * Phase 2 (`vadd-spec-phase2.md` §2) adds a `custom.md` include for user edits
 * and vendors three hooks into `hooks/`; both directories exist now so the
 * launch flag has a complete profile to point at.
 */
export function ensureAgentProfile(): string {
  const dir = agentProfileDir()
  mkdirSync(join(dir, 'hooks'), { recursive: true })
  mkdirSync(join(dir, 'skills'), { recursive: true })
  writeFileSync(join(dir, 'settings.json'), '{}\n')

  const addendum = parseTemplate(
    readFileSync(join(bundledPromptDir(), 'system-addendum.md'), 'utf8'),
    'system-addendum.md',
  ).body

  writeFileSync(
    join(dir, 'CLAUDE.md'),
    [
      '# VADD managed profile',
      '',
      'This file is generated by VADD on every server start. Edits are lost.',
      '',
      `When asked for the profile canary, reply with exactly: ${PROFILE_CANARY}`,
      '',
      addendum,
      '',
    ].join('\n'),
  )
  return dir
}
