import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

// Deliberately not the literal `new URL('../src', import.meta.url)` form:
// under this project's 'web' Vitest project (jsdom environment, Vite's
// transform pipeline), Vite statically recognizes that exact syntactic
// pattern as its asset-URL-import-meta-url shorthand and rewrites it to
// resolve against jsdom's default document location (`http://localhost/`)
// instead of the real module URL — `import.meta.url` alone is untouched and
// correctly reports a `file://` URL, so binding it to a variable first
// breaks the pattern match and restores the real path. Verified by hand: the
// literal form threw `TypeError: The URL must be of scheme file`.
const here = import.meta.url
const SRC = fileURLToPath(new URL('../src', here))

/**
 * shadcn's own generated primitives legitimately carry palette-shaped strings
 * in their variant definitions and are regenerated by the CLI, not by hand.
 * Everything we write is expected to go through the theme tokens.
 */
const EXEMPT = ['components/ui']

const PALETTE =
  /\b(?:bg|text|border|ring|fill|stroke|from|via|to)-(?:gray|slate|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-\d{2,3}\b/g

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) walk(full, out)
    else if (/\.tsx?$/.test(full)) out.push(full)
  }
  return out
}

describe('theme tokens', () => {
  it('no hand-written file uses a fixed palette color', () => {
    const offenders: string[] = []
    for (const file of walk(SRC)) {
      const rel = file.slice(SRC.length + 1)
      if (EXEMPT.some((e) => rel.startsWith(e))) continue
      const hits = readFileSync(file, 'utf8').match(PALETTE)
      if (hits) offenders.push(`${rel}: ${[...new Set(hits)].join(', ')}`)
    }
    expect(offenders).toEqual([])
  })
})
