import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { contractReference } from '@vadd/core'
import { vaddHome } from '../../paths.js'
import { bundledPromptDir, parseTemplate } from '../../prompts/renderer.js'
import type { AgentKindConfig } from './types.js'

/**
 * A token only VADD's own generated Codex AGENTS.md contains. Distinct from
 * `PROFILE_CANARY` (Claude Code's own, `profile.ts`) so the two isolation
 * mechanisms are independently provable rather than one test accidentally
 * passing against the other agent's profile.
 */
export const CODEX_PROFILE_CANARY = 'VADD-CODEX-PROFILE-CANARY-9d2e47'

/** `~/.vadd/agent-profiles/codex`, mirroring `agentProfileDir()` in `profile.ts`. */
function codexProfileDir(): string {
  return join(vaddHome(), 'agent-profiles', 'codex')
}

export function codexConfig(): AgentKindConfig {
  return {
    kind: 'codex',
    packageName: '@agentclientprotocol/codex-acp',
    missingAdapterMessage:
      'Cannot find the Codex ACP adapter. Install it with: pnpm add -Dw @agentclientprotocol/codex-acp',
    setupProfile: () => {
      const dir = codexProfileDir()
      mkdirSync(dir, { recursive: true })

      // Isolation, not preference — same reasoning as Claude Code's
      // ensureAgentProfile(): the user's real ~/.codex must stay untouched by
      // a VADD session, while login must still work.
      const realHome = process.env.CODEX_HOME ?? join(homedir(), '.codex')
      const authSrc = join(realHome, 'auth.json')
      if (existsSync(authSrc)) {
        copyFileSync(authSrc, join(dir, 'auth.json'))
      }

      // Codex's contract-addendum delivery: on every session it builds a
      // merged instruction chain from $CODEX_HOME/AGENTS.override.md (global
      // scope) concatenated with any project-level AGENTS.md files in the
      // repo being worked on — verified against OpenAI's own docs
      // (developers.openai.com/codex/guides/agents-md). AGENTS.override.md,
      // not AGENTS.md, so a target repo's own AGENTS.md (if it has one) is
      // still additionally discovered rather than shadowed outright — the
      // override file always wins at the global-scope layer regardless of
      // what else CODEX_HOME might also contain.
      const addendum = parseTemplate(
        readFileSync(join(bundledPromptDir(), 'system-addendum.md'), 'utf8'),
        'system-addendum.md',
      ).body

      writeFileSync(
        join(dir, 'AGENTS.override.md'),
        [
          '# VADD managed profile',
          '',
          'This file is generated by VADD on every server start. Edits are lost.',
          '',
          `When asked for the profile canary, reply with exactly: ${CODEX_PROFILE_CANARY}`,
          '',
          addendum,
          '',
          '## Event reference',
          '',
          'Generated from the schema. These are the only fields each event accepts,',
          'and the caps are enforced — a longer string is rejected and the whole',
          'block is lost.',
          '',
          contractReference(),
          '',
        ].join('\n'),
      )

      return { env: { CODEX_HOME: dir } }
    },
  }
}
